
CC=gcc
CFLAGS=

all: clean

clean:
	rm -rf exam2-6 exam2-7\
	       prac2-1 prac2-2 prac2-3 prac2-4 prac2-5 prac2-6 \
	       prac2-7 prac2-8 prac2-9 prac2-10 prac2-15 prac2-16

exam2-6: exam2-6.c
	$(CC) $(CFLAGS) $@.c -o $@

exam2-7: exam2-7.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-1: prac2-1.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-2: prac2-2.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-3: prac2-3.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-4: prac2-4.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-5: prac2-5.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-6: prac2-6.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-7: prac2-7.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-8: prac2-8.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-9: prac2-9.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-10: prac2-10.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-15: prac2-15.c
	$(CC) $(CFLAGS) $@.c -o $@

prac2-16: prac2-16.c
	$(CC) $(CFLAGS) $@.c -o $@
