all: clean

clean:
	rm -rf prac2-1 prac2-2 prac2-3 prac2-4 prac2-5 prac2-6

prac2-1: prac2-1.c
	gcc prac2-1.c -o prac2-1

prac2-2: prac2-2.c
	gcc prac2-2.c -o prac2-2

prac2-3: prac2-3.c
	gcc prac2-3.c -o prac2-3

prac2-4: prac2-4.c
	gcc prac2-4.c -o prac2-4

prac2-5: prac2-5.c
	gcc prac2-5.c -o prac2-5

prac2-6: prac2-6.c
	gcc prac2-6.c -o prac2-6
