CC=gcc
CFLAGS=

all: clear

clear:
	rm -rf exam4-7 exam4-8 \
				 prac4-6

exam4-7: exam4-7.c
	$(CC) $(CFLAGS) $@.c -o $@

exam4-8: exam4-8.c
	$(CC) $(CFLAGS) $@.c -o $@

prac4-6: prac4-6.c
	$(CC) $(CFLAGS) $@.c -o $@
