all: clean

clean:
	rm -rf example1-2 prac1-5 prac1-7 prac1-8

example1-2: example1-2.c
	gcc example1-2.c -o example1-2

prac1-5: prac1-5.c
	gcc prac1-5.c -o prac1-5

prac1-7: prac1-7.c
	gcc prac1-7.c -o prac1-7

prac1-8: prac1-8.c
	gcc prac1-8.c -o prac1-8
