all: clean

clean:
	rm -rf example1-2 example1-3 example1-4 example1-5\
	  prac1-5 prac1-7 prac1-8 prac1-9 prac1-10

example1-2: example1-2.c
	gcc example1-2.c -o example1-2

example1-3: example1-3.c
	gcc example1-3.c -o example1-3

example1-4: example1-4.c
	gcc example1-4.c -o example1-4

example1-5: example1-5.c
	gcc example1-5.c -o example1-5

prac1-5: prac1-5.c
	gcc prac1-5.c -o prac1-5

prac1-7: prac1-7.c
	gcc prac1-7.c -o prac1-7

prac1-8: prac1-8.c
	gcc prac1-8.c -o prac1-8

prac1-9: prac1-9.c
	gcc prac1-9.c -o prac1-9

prac1-10: prac1-10.c
	gcc prac1-10.c -o prac1-10

prac1-11: prac1-11.c
	gcc prac1-11.c -o prac1-11
